### ISSUE TITLE
You need to update model listing

### ISSUE THREAD

**Issue by Phouter0499** [macro21KGB/select-and-complete#1]
gpt-4o-mini is now the cheapest model and better than any version of gpt 3 and gpt 4 (without the 'o').
I think you should allow the user to just paste in the model string name so you don't need to keep updating the listing.

**Comment by macro21KGB** [comment]
You're right, I will push an update tomorrow to let the user type the model, thank you for your feedback

**Comment by macro21KGB** [comment]
In the latest update, i have updated the model list and added the option to use custom model name, let me know if there is some other bug.
