### ISSUE TITLE
undefined (reading '0')

### ISSUE THREAD

**Issue by Phouter0499** [macro21KGB/select-and-complete#2]
I'm using an openai model and got this error:
```
TypeError: Cannot read properties of undefined (reading '0')
    at OpenAIModel.generate (plugin:select-and-complete:107:32)
    at async SelectAndCompletePlugin.completeText (plugin:select-and-complete:297:23)
    at async HTMLDivElement.eval (plugin:select-and-complete:356:7)
```

I think the issue is this line of code:
`return message.json.content[0].text;`
Openai probably changed their response structure. Look here: https://platform.openai.com/docs/api-reference/chat/create
Also max_tokens is deprecated

**Comment by macro21KGB** [comment]
I'll change it right away, again thank you for letting me know

**Comment by macro21KGB** [comment]
i changed the line to:
```ts
return message.choices[0].message.content
```

**Comment by macro21KGB** [comment]
update is out, let me know if that has fixed the error

**Comment by Phouter0499** [comment]
You need to convert to json:
message.json.choices[0].message.content;

**Comment by macro21KGB** [comment]
changed, take a look

**Comment by Phouter0499** [comment]
It all works now thanks.

**Comment by Phouter0499** [comment]
Closing

**Comment by Phouter0499** [comment]
Closing
